globalvar g1;
globalvar g2;
globalvar g3;
globalvar g4;
globalvar g5;
globalvar g6;
g1=Lupikan;
g2=Myython;
g3=Lidd;
g4=Krothonias;
g5=Kythoness;
g6=Niddony;
global.hepsinisec1=false;
global.hepsinisec2=false;
global.jumpingmode=false;